In [1]:
import tensorflow as tf

# **Checking the version of TensorFlow**

In [2]:
print(tf.__version__)

2.8.2


# **Tensors**



*   **A Tensor is a multi-dimensional array**
*   **Similar to NumPy ndarray objects, tf.Tensor objects have a data type and a shap**e. 

*   **tf.Tensors can reside in accelerator memory (like a GPU)**
*   **Any operations performed on a python datatype using tf.math or tf.linalg converts them to tf.tensor object**





### **Creating Tensors**

In [3]:
a = tf.constant([1,2,3],dtype=tf.float32)

In [4]:
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [5]:
b = tf.constant([1,2,3,4],shape=(2,2),dtype=tf.int32) 

In [6]:
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [7]:
b.shape

TensorShape([2, 2])

# **Keras**



* Keras is an High level API for creating Artifical Neural Networks   
*  Keras is integrated and is readily available with TF 2.0
*   Keras makes our task so simple using the help of Object Oriented Approach 





In [8]:
from tensorflow import keras

# **Training our first Neural Network**

## **Task-1:**
## **Using Neural Network to predict a simple function f(x)=2x+1**

### **Defining Input and Output** 


*   **x is usually the input and y is the output**
*   **x is called as features**
*   **Learning is done by looking at the eaxmples**
*   **This x and y are called as training data**
*   **Learning from examples is called Supervised Learning**
*   **We are currently doing Deep Suprvised Learning**







In [9]:
import numpy as np

In [10]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([3,5,7,9,11,13,15,17,19,21])

In [11]:
x.shape

(10,)

In [12]:
y.shape

(10,)

### **Keras Layer Sequential Objects** 



*   **Layers API allows us to define neural networks as layers**
*   **Sequential objects define models that  are sequential without branches**



In [13]:
model = keras.models.Sequential([
                                 keras.layers.Dense(units=1,input_shape=(1,))
])

### **Compiling the Model**



*   **Compiling allows us to give parameters like loss optimizer 
and evalution metrics**
*   **loss tell how close our predicted value is to real value**
*   **optimizer helps us to minimize the loss**
*   **evaluation metrics helps us to measure our model's performance**






In [14]:
loss = keras.losses.MeanSquaredError()
optimizer = keras.optimizers.SGD()

In [15]:
model.compile(loss=loss,optimizer=optimizer)

### **Training the model**



*   **Finally let us train our neural network to learn the function**
*   **training is very simple and can be done by calling a function called as fit**
*   **We will no of steps the model needs to update the weights by the help of epochs parameter**


In [16]:
model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 478ms/step - loss: 257.6083
Epoch 2/500
1/1 [==============================] - 0s 16ms/step - loss: 11.9014
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6273
Epoch 4/500
1/1 [==============================] - 0s 12ms/step - loss: 0.1094
Epoch 5/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0850
Epoch 6/500
1/1 [==============================] - 0s 19ms/step - loss: 0.0832
Epoch 7/500
1/1 [==============================] - 0s 20ms/step - loss: 0.0824
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0817
Epoch 9/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0810
Epoch 10/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0804
Epoch 11/500
1/1 [==============================] - 0s 11ms/step - loss: 0.0797
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 0.0790
Epoch 13/500
1/1 [=============================

### **Lets use our model to predict f(x) when x=100 which should be 201**

In [18]:
model.predict([20])

array([[41.145245]], dtype=float32)